#!/usr/bin/env bash
# check_doc_for_targets.sh.sh: Validate that the make command are documented as expected
set -eu -o pipefail

# Prints the provided error message and exit with the exit code 1
function print_error_and_exit() {
  local message="${1}"
  echo "ERROR: ${message}"
  exit 1
}

target_list=("$@")

test "${#target_list[@]}" -gt 0 || print_error_and_exit "No targets provided as argument."

for target in "${target_list[@]}"
do
  ## Check for Makefile comments: each target line must have a comment
  grep -q "^${target}:.*##.*" ./Makefile || print_error_and_exit "No comment found for target ${target} in ./Makefile"

  ## Check that there is make help command
  make help 2>&1 | grep -q "${target}" || print_error_and_exit "No entry found for target ${target} in make help command"

  ## Check that README mentions the target
  grep -q "${target}" ./README.md || print_error_and_exit "No mention of target ${target} found in ./README.md"
done

echo "SUCCESS"
exit 0