name: module3_task4
on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: cd module3_task4 && sudo ./setup.sh
      - run: cd module3_task4 && make build
      - run: cd module3_task4 && make clean
      - run: cd module3_task4 && make POST_NAME=name POST_TITLE=title post
      - run: cd module3_task4 && make help
      - run: cd module3_task4 && make hello
      - run: cd module3_task4 && make package
      - run: cd module3_task4 && make lint
      - run: cd module3_task4 && make unit-tests
      - run: cd module3_task4 && make integration-tests
      - run: cd module3_task4 && make validate
